/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 02 04:36:13 GMT 2018
 */

package com.ib.client;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.ib.client.EClientErrors;
import com.ib.client.EException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class EException_ESTest extends EException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      EClientErrors.CodeMsgPair eClientErrors_CodeMsgPair0 = new EClientErrors.CodeMsgPair((-381), "U<R[+");
      EException eException0 = new EException(309, eClientErrors_CodeMsgPair0);
      int int0 = eException0.getId();
      assertEquals(309, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      EException eException0 = new EException((-2234), 94, "/YP");
      int int0 = eException0.getId();
      assertEquals((-2234), int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      EClientErrors.CodeMsgPair eClientErrors_CodeMsgPair0 = new EClientErrors.CodeMsgPair(1773, "Y{@]z}+;_");
      EException eException0 = new EException(1773, eClientErrors_CodeMsgPair0);
      int int0 = eException0.getErrorCode();
      assertEquals(1773, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      EException eException0 = new EException("");
      int int0 = eException0.getErrorCode();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      EException eException0 = null;
      try {
        eException0 = new EException(1891, (EClientErrors.CodeMsgPair) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.ib.client.EException", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      EClientErrors.CodeMsgPair eClientErrors_CodeMsgPair0 = new EClientErrors.CodeMsgPair(0, "%s [id = %d, errorCode = %d]");
      EException eException0 = new EException(0, eClientErrors_CodeMsgPair0);
      String string0 = eException0.getMessage();
      assertEquals("%s [id = %d, errorCode = %d] [id = 0, errorCode = 0]", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      EClientErrors.CodeMsgPair eClientErrors_CodeMsgPair0 = new EClientErrors.CodeMsgPair(0, "%s [id = %d, errorCode = %d]");
      EException eException0 = new EException(0, eClientErrors_CodeMsgPair0);
      int int0 = eException0.getErrorCode();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      EClientErrors.CodeMsgPair eClientErrors_CodeMsgPair0 = new EClientErrors.CodeMsgPair(0, "%s [id = %d, errorCode = %d]");
      EException eException0 = new EException(0, eClientErrors_CodeMsgPair0);
      int int0 = eException0.getId();
      assertEquals(0, int0);
  }
}
